<a href="https://colab.research.google.com/github/mayank-0407/ML-Lab/blob/main/ML_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5])
rev_arr=arr[::-1]
print(rev_arr)

[5 4 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [8]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1_flatten = array1.flatten()
array1_ravel = array1.ravel()
print(array1_flatten)
print(array1_ravel)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [16]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
print(arr1==arr2)

[[ True  True]
 [ True  True]]


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [17]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique_values_x, counts_x = np.unique(x, return_counts=True)
unique_values_y, counts_y = np.unique(y, return_counts=True)

most_frequent_value_x = unique_values_x[np.argmax(counts_x)]
most_frequent_indices_x = np.where(x == most_frequent_value_x)[0]

most_frequent_value_y = unique_values_y[np.argmax(counts_y)]
most_frequent_indices_y = np.where(y == most_frequent_value_y)[0]

print("Array x:")
print("Most frequent value:", most_frequent_value_x)
print("Indices of the most frequent value:", most_frequent_indices_x)

print("\nArray y:")
print("Most frequent value:", most_frequent_value_y)
print("Indices of the most frequent value:", most_frequent_indices_y)

Array x:
Most frequent value: 1
Indices of the most frequent value: [0 5 7 8 9]

Array y:
Most frequent value: 1
Indices of the most frequent value: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [25]:
arr = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all_elements = np.sum(arr)
print("Sum of all Elements ",sum_all_elements)
print()

sum_row_wise = np.sum(arr, axis=1)
print("Row Wise Sum of the Matrix",sum_row_wise)

sum_col_wise = np.sum(arr, axis=0)
print()
print("Column Wise Sum of the Matrix",sum_col_wise)

Sum of all Elements  45

Row Wise Sum of the Matrix [[14]
 [16]
 [15]]

Column Wise Sum of the Matrix [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [28]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
sum_diagonal = np.trace(n_array)
print("Sum of Diagonal Elements ",sum_diagonal)

eigenvalues = np.linalg.eigvals(n_array)
print("Eigen Values of Matrix",eigenvalues)

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigen Vectors of Matrix",eigenvectors)

inverse_matrix = np.linalg.inv(n_array)
print("Inverse of Matrix",inverse_matrix)

determinant = np.linalg.det(n_array)
print("Determinant of Matrix",determinant)

Sum of Diagonal Elements  176
Eigen Values of Matrix [98.16835147 28.097044   49.73460452]
Eigen Vectors of Matrix [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of Matrix [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of Matrix 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]
    q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]
    q = [[4, 5, 1], [6, 7, 2]]

In [35]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])

matrix_product = np.dot(p, q)
covariance_matrix = np.cov(matrix_product,rowvar=False)

print("Matrix product (p * q):")
print(matrix_product)

print("\nCovariance matrix between p and q:")
print(covariance_matrix)

Matrix product (p * q):
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance matrix between p and q:
[[233.33333333 280.          70.        ]
 [280.         336.          84.        ]
 [ 70.          84.          21.        ]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [38]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.inner(x, y)
outer_product = np.outer(x, y)
cartesian_product = np.transpose([np.tile(x, len(y.flatten())), np.repeat(y, len(x.flatten()), axis=0)])

print("\nInner product:")
print(inner_product)

print("\nOuter product:")
print(outer_product)

print("\nCartesian product:")
print(cartesian_product)


Inner product:
[[17 52]
 [13 62]]

Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product:
[array([[2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4],
        [3, 2, 9, 3, 2, 9, 3, 2, 9, 3, 2, 9, 3, 2, 9, 3, 2, 9]])
 array([[ 1,  5,  0],
        [ 1,  5,  0],
        [ 1,  5,  0],
        [ 1,  5,  0],
        [ 1,  5,  0],
        [ 1,  5,  0],
        [ 5, 10,  3],
        [ 5, 10,  3],
        [ 5, 10,  3],
        [ 5, 10,  3],
        [ 5, 10,  3],
        [ 5, 10,  3]])]


/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


**Q2: Based on NumPy Mathematics and Statistics**

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [41]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)

print("Element-wise absolute value:")
print(abs_array)

# ii. Percentiles for flattened array, columns, and rows
percentiles_flattened = np.percentile(array, [25, 50, 75])
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

print("\nPercentiles for the flattened array:")
print(percentiles_flattened)

print("\nPercentiles for each column:")
print(percentiles_columns)

print("\nPercentiles for each row:")
print(percentiles_rows)

# iii. Mean, Median, and Standard Deviation for flattened array, columns, and rows
mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_dev_flattened = np.std(array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_dev_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_dev_rows = np.std(array, axis=1)

print("\nMean, Median, and Standard Deviation for the flattened array:")
print("Mean:", mean_flattened)
print("Median:", median_flattened)
print("Standard Deviation:", std_dev_flattened)

print("\nMean, Median, and Standard Deviation for each column:")
print("Mean:", mean_columns)
print("Median:", median_columns)
print("Standard Deviation:", std_dev_columns)

print("\nMean, Median, and Standard Deviation for each row:")
print("Mean:", mean_rows)
print("Median:", median_rows)
print("Standard Deviation:", std_dev_rows)

Element-wise absolute value:
[[1 2 3]
 [4 5 6]]

Percentiles for the flattened array:
[-3.5 -0.5  2.5]

Percentiles for each column:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles for each row:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean, Median, and Standard Deviation for the flattened array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Mean, Median, and Standard Deviation for each column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Mean, Median, and Standard Deviation for each row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).

Find floor, ceiling
and truncated value, rounded values

In [42]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print("Original array:",a)
print("\nFloor values:",floor_values)
print("\nCeiling values:",ceiling_values)
print("\nTruncated values:",truncated_values)
print("\nRounded values:",rounded_values)

Original array: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor values: [-2. -2. -1.  0.  1.  1.  3.]

Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]

Truncated values: [-1. -1. -0.  0.  1.  1.  3.]

Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


**Q3: Based on Searching and Sorting**

**(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find**

i. Sorted array

In [49]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
new_arr=np.sort(arr)
print("Sorted Arr",new_arr)

Sorted Arr [ 10  16  16  52  54  62 453]


ii. Indices of sorted array

In [50]:
sorted_indices = np.argsort(new_arr)
print("Sorted Indices of The elements",sorted_indices)

Sorted Indices of The elements [0 1 2 3 4 5 6]


iii. 4 smallest elements

In [51]:
smallest_elements = new_arr[:4]
print("Smallest Elements : ",smallest_elements)

Smallest Elements :  [10 16 16 52]


iv. 5 largest elements

In [52]:
largest_elements = new_arr[-5:]
print("5 Lagest Elements of Arr ",largest_elements)

5 Lagest Elements of Arr  [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

In [54]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array.astype(int) == array]

print("Only Integer Elements in Array ",integer_elements)

Only Integer Elements in Array  [1. 2. 3. 2.]


ii. Float elements only

In [55]:
float_elements = array[array.astype(int) != array]

print("Only Float Elements in Array ",float_elements)

Only Float Elements in Array  [1.2 2.2]
